### ISSUE TITLE
https://github.com/INTERPOL-Innovation-Centre/OSINT-Framework

### ISSUE THREAD

**Issue by andre-santos1** [INTERPOL-Innovation-Centre/Relevant-Open-Source-projects-for-LEAs#1]
Looks like https://github.com/INTERPOL-Innovation-Centre/OSINT-Framework is down. How can I access it?

**Comment by VinceICPO** [comment]
@andre-santos1, this is actually a private repository and only our LEA invited members may access this repo.
If you are LEA, contact us and we will see how to invite you.
Best,

**Comment by andre-santos1** [comment]
Hi @VinceICPO I´m a LEA. How should I proceed?

**Comment by VinceICPO** [comment]
please email us at cntl@interpol.int. Thanks.
